### ISSUE TITLE
The panel for ControlNet starts expanded by default if it's the only extension

### ISSUE THREAD

**Issue by EfourC** [shirayu/sd-webui-enable-checker#16]
I just updated this extension and discovered that it causes the ControlNet panel to be expanded by default, which is unwanted.

If I also install or enable something else, like the Unprompted or Anti Burn extensions, the problem doesn't happen.

### To Reproduce
1. Have ControlNet be the only extension with a panel in the txt2img tab.
2. Install/enable the `sd-webui-enable-checker` extension
3. Click `Apply and Restart`, or restart the WebUI process completely

### Expected behavior
The ControlNet panel shouldn't be expanded by default

### Environment
- Windows 10
- stable-diffusion-webui Version: commit: [22bcc7be](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/22bcc7be428c94e9408f589966c2040187245d81)
- sd-webui-enable-checker Version: e4c3fa60 (Fri Mar 31 17:58:55 2023)

### Additional context

![69FiT4jn0P](https://user-images.githubusercontent.com/121468033/229253276-df479dca-15b8-49cc-b4b9-a54351af4674.png)
![tEwNJMdLgR](https://user-images.githubusercontent.com/121468033/229253320-3ebe6a50-a58b-4542-950f-2f4dc916134d.png)
![e7JXGRZM01](https://user-images.githubusercontent.com/121468033/229253341-8ded27b4-2a1a-4f4d-a9c7-d3739d4dc6f0.png)

**Comment by shirayu** [comment]
Thanks for the report.
The problem was not reproduced in my environment, but I updated to e43b6b1 by adding the status check.
Please try it.

**Comment by EfourC** [comment]
Just tried but I still see the problem, how strange!

I see it with only ControlNet and enable-checker enabled (plus the built-in extensions).
Same result with Firefox, Brave, and ungoogled-chromium browsers.

Any suggestions of what I should check for to help debug it?

**Comment by EfourC** [comment]
One more detail to be clear, if I have only one other extension enabled that is not ControlNet, it doesn't show the problem.

For example, enabled-checker + Anti Burn:  Anti Burn panel is collapsed by default like normal).

**Comment by shirayu** [comment]
Thanks for the detailed information.
I may have found the reason.
It's probably here.
https://github.com/shirayu/sd-webui-enable-checker/blob/5c96b1df23a0c3a8e4b03f892575c8f56767eca0/javascript/main.js#L169

I will look for a solution.

**Comment by shirayu** [comment]
I updated the code to 8af7849.
How about that?

**Comment by EfourC** [comment]
Looks good now, thanks!
