### ISSUE TITLE
Feedback: Theme changes

### ISSUE THREAD

**Issue by guzuligo** [shirayu/sd-webui-enable-checker#6]
skyblue looks bad as it conflicts with white text as I am using dark theme,

I changed the colors used as follows:
const color_enable = "black";
const color_disable = "";

This way, only active one gets highlighted and it looks amazing. 👍

**Comment by shirayu** [comment]
Thank you for the feedback!
I added the case for the dark mode :smile:

**Comment by guzuligo** [comment]
I still edited the code to
color_disable = "" 😜

**Comment by shirayu** [comment]
Year, It would be nice to be able to set color preferences. :smiley: 
I opened #9.
