### ISSUE TITLE
Unreadable in Dark UI

### ISSUE THREAD

**Issue by MrKuenning** [shirayu/sd-webui-enable-checker#7]
When the web UI is in dark mode. It's white text on a light grey box.

Could this change extension be used to change the text color instead of a highlight box around the text?

It would be nice if there were setting adjustment that allows users to choose their own colors.
As well as an option to choose if the text color changes or if it's a highlight that changes.

I know for me, I would set the colors to stay default when disabled and set the titles to change to a color when enabled.

**Comment by theFuzzyWarble** [comment]
I added a little tweak to mine for dark mode @ .\automatic1111\extensions\sd-webui-enable-checker\javascript\\[main.js](https://github.com/theFuzzyWarble/sd-webui-enable-checker/blob/main/javascript/main.js):
Hope that helps.

**Comment by shirayu** [comment]
Please try the latest version.
I updated at #6.

**Comment by abvgdeabvgde2** [comment]
URL check is not reliable. This doesn't work if the theme is set by Windows system settings rather than URL query. I failed to find a solution myself. The dirty workaround would be to check the current background color.

**Comment by shirayu** [comment]
Good suggestion!
I updated at 48847ad
